title: "Simple Secret Stack"
description: "This example stack shows the minimum configuration needed for the secret module. Assumes an existing vault and AES key"
schemaVersion: 1.1.0
version: "20190404" 


locale: en

variableGroups:
  - title: "RM controlled Vars"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - current_user_ocid
      - fingerprint
      - private_key_path
  
  - title: "VCN config"
    variables:
      - network_compartment
      - vcn


variables:
  #"RM controlled Vars"
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: OCID of the tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: region to create resources
    required: true

  current_user_ocid:
    type: string

  fingerprint:
    type: string
    default: " "

  private_key_path:
    type: string
    default: " "


  network_compartment:
    type: oci:identity:compartment:id
    default: tenancy_ocid

  vcn: 
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: network_compartment